name: "File Sync to VPS"

description: "Sync files from the repository to a VPS using rsync over SSH."

inputs:
  SSH_USERNAME:
    description: "Username for the SSH connection"
    required: true
  SSH_IPADDRESS:
    description: "IP address of the VPS"
    required: true
  SSH_PASSWORD:
    description: "Password for the SSH connection"
    required: true
  LOCAL_PATH:
    description: "Path to the local files to be synced"
    required: true
  REMOTE_PATH:
    description: "Destination path on the VPS"
    required: true

runs:
  using: "node16"
  main: "main.js"
