name: Deploy on Push

on:
  push:
    branches:
      - main # Adjust to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Joke
      uses: Sayemahamed/skills-write-javascript-actions/.github/actions/joke-action